use_frameworks!

platform :ios, '11.0'

target 'RZColorful_Example' do
  pod 'RZColorful', :path => '../'
  pod 'Masonry'
  target 'RZColorful_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
